# Get Started

In [1]:
# pylint: disable=W0104
import sys
sys.path.append("../")

import numpy as np
from quditop.gates import H, X, Y, Z, RX, RY, RZ, UMG, SWAP, MVCG, GP
from quditop.circuit import Circuit

In [2]:
dim = 3
n_qudits = 3

ctrl_qudits = 0
ctrl_states = 1
cir = Circuit(dim, n_qudits, gates=[
    X(dim, [0,1]).on(1),
    SWAP(dim, [0,1]).on([1, 2], ctrl_qudits, ctrl_states)
])

qs1 = cir.get_qs(ket=True)
print(f"No valid control:\n{qs1}")

cir2 = Circuit(dim, n_qudits, gates=[
    X(dim, [0, ctrl_states]).on(0),
    X(dim, [0, 1]).on(1),
    SWAP(dim).on([1, 2], ctrl_qudits, ctrl_states)
])

qs2 = cir2.get_qs(ket=True)
print(f"No valid control:\n{qs2}")

No valid control:
1¦010⟩
No valid control:
1¦101⟩


In [3]:
# Build a quantum circuit

dim = 2
n_qudits = 4

circ = Circuit(dim, n_qudits, gates=[
    H(dim, [0,1]).on(0),
    X(dim, [0,1]).on(0, [2,3], [1, 1]),
    Y(dim, [0,1]).on(1),
    Z(dim, [0,1]).on(1, 2, 1),
    RX(dim, [0,1], pr='param').on(3),
    RY(dim, [0,1], pr=1.0).on(2, 3, 1),
    X(dim, [0,1]).on(1, [0, 2, 3], 1),
    RY(dim, [0,1], pr=2.0).on(3, [0, 1, 2], 1)
])

print(circ)

Circuit(
  (gates): ModuleList(
    (0): H(2|0)
    (1): X(2 [0 1]|0 <-: 2 3 - 1 1)
    (2): Y(2 [0 1]|1)
    (3): Z(2 [0 1]|1 <-: 2 - 1)
    (4): RX(2 [0 1] param|3)
    (5): RY(2 [0 1] 1|2 <-: 3 - 1)
    (6): X(2 [0 1]|1 <-: 0 2 3 - 1 1 1)
    (7): RY(2 [0 1] 2|3 <-: 0 1 2 - 1 1 1)
  )
)


In [4]:
# print the parameter names, where the `_param_` is default name.

circ.param_name

['param', '1', '2']

In [5]:
# We can add new gate(s) or circuit to old circuit easily.
# circ = Circuit(dim, n_qudits)

circ += RZ(dim, [0, 1], pr='pr_z').on(3)
circ.append(RX(dim, [0, 1], pr=2.0).on(2))
circ += X(dim, [0, 1]).on(2)
circ += Y(dim, [0, 1]).on(0, 3)
circ += Circuit(dim, n_qudits, gates=[Z(dim, [0, 1]).on(1), Z(dim, [0, 1]).on(2)])

print(circ)

Circuit(
  (gates): ModuleList(
    (0): H(2|0)
    (1): X(2 [0 1]|0 <-: 2 3 - 1 1)
    (2): Y(2 [0 1]|1)
    (3): Z(2 [0 1]|1 <-: 2 - 1)
    (4): RX(2 [0 1] param|3)
    (5): RY(2 [0 1] 1|2 <-: 3 - 1)
    (6): X(2 [0 1]|1 <-: 0 2 3 - 1 1 1)
    (7): RY(2 [0 1] 2|3 <-: 0 1 2 - 1 1 1)
    (8): RZ(2 [0 1] pr_z|3)
    (9): RX(2 [0 1] 2|2)
    (10): X(2 [0 1]|2)
    (11): Y(2 [0 1]|0 <-: 3 - 1)
    (12): Z(2 [0 1]|1)
    (13): Z(2 [0 1]|2)
  )
)


In [6]:
# print the summary of circuit.

circ.summary()

=================Circuit Summary=================
|Total number of gates   : 14.                  |
|Parameter gates         : 5.                   |
|with 5 parameters are   :                      |
|param, 1, 2, pr_z, 2                         . |
|Number qudits of circuit: 4                    |


In [7]:
# Get the quantum state of circuit.
print(f"quantum state in numpy.array:\n{circ.get_qs()}\n")
print(f"quantum state in ket:\n{circ.get_qs(ket=True)}")

quantum state in numpy.array:
[ 0.        +0.j          0.        +0.j          0.        +0.j
  0.        +0.j         -0.59500982+0.j          0.        +0.j
  0.        +0.38205145j  0.        +0.j          0.        +0.j
  0.        +0.j          0.        +0.j          0.        +0.j
 -0.59500982+0.j          0.        +0.j          0.        +0.38205145j
  0.        +0.j        ]

quantum state in ket:
-0.595¦0100⟩
0.3821j¦0110⟩
-0.595¦1100⟩
0.3821j¦1110⟩


In [8]:
# We can get the state of quantum with specific value.
default_value = 0.0
qs = circ.get_qs({'param': 1.0}, endian_reverse=True)

print(f'n_qudits: {circ.n_qudits}')
print(f'qs:\n{qs}')

n_qudits: 4
qs:
[ 0.        +0.j          0.        +0.j         -0.52217023+0.j
 -0.52217023+0.j          0.        +0.j          0.        +0.j
  0.        +0.33528168j  0.        +0.33528168j  0.        -0.08781409j
  0.        +0.j          0.25034175+0.j         -0.25034175-0.08781409j
  0.13676233+0.j          0.        +0.j          0.        -0.1607426j
  0.13676233+0.1607426j ]


In [9]:
# print the trainable parameters, this interface inherits from torch.nn.Module.
list(circ.parameters())

[Parameter containing:
 tensor([1.], requires_grad=True),
 Parameter containing:
 tensor([1.], requires_grad=True),
 Parameter containing:
 tensor([2.], requires_grad=True),
 Parameter containing:
 tensor([0.], requires_grad=True),
 Parameter containing:
 tensor([2.], requires_grad=True)]

In [10]:
# Get the parameters of circuit.
# Warn: The return is a dictionay, if two parameters with same name, the second one will overwrite the first one.

print(circ.get_parameters())

{'param': 1.0, '1': 1.0, '2': 2.0, 'pr_z': 0.0}


In [11]:
# Convert the circuit to encoder, we can see that there's no `requires_grad` for parameters.
circ.as_encoder()
# You can also do it by method `circ.no_grad()`
list(circ.parameters())

[Parameter containing:
 tensor([1.]),
 Parameter containing:
 tensor([1.]),
 Parameter containing:
 tensor([2.]),
 Parameter containing:
 tensor([0.]),
 Parameter containing:
 tensor([2.])]

In [12]:
# QuditWorld support qudits.
import torch

dim = 3
n_qudits = 4

circ2 = Circuit(dim, n_qudits, gates=[
    UMG(dim, mat=torch.randn(dim, dim)).on(2),
    UMG(dim, mat=torch.randn(dim, dim)).on(0, ctrl_qudits=2, ctrl_states=1),
    RX(dim, [1, 2], pr=1.0).on(2),
    RY(dim, [0, 2]).on(3, 2),
    RZ(dim, [0, 1]).on(3, 2),
    GP(dim, pr="gh_pr").on(3),
])

print(f"circ2:\n{circ2}")
print(f"circ2 qs:\n{circ2.get_qs()}")

circ2:
Circuit(
  (gates): ModuleList(
    (0): UMG(3|2)
    (1): UMG(3|0 <-: 2 - 1)
    (2): RX(3 [1 2] 1|2)
    (3): RY(3 [0 2] _param_|3 <-: 2 - 2)
    (4): RZ(3 [0 1] _param_|3 <-: 2 - 2)
    (5): GP(3 gh_pr|3)
  )
)
circ2 qs:
[-1.38604367+0.j          0.        +0.j          0.        +0.j
 -0.32533786+0.07461847j  0.        +0.j          0.        +0.j
 -0.13658818+0.17773289j  0.        +0.j          0.        +0.j
  0.        +0.j          0.        +0.j          0.        +0.j
  0.        +0.j          0.        +0.j          0.        +0.j
  0.        +0.j          0.        +0.j          0.        +0.j
  0.        +0.j          0.        +0.j          0.        +0.j
  0.        +0.j          0.        +0.j          0.        +0.j
  0.        +0.j          0.        +0.j          0.        +0.j
  0.        +0.j          0.        +0.j          0.        +0.j
 -0.27681784+0.j          0.        +0.j          0.        +0.j
  0.        +0.15122628j  0.        +0.j          0.  

In [13]:
# Note: In QudiTop, we don't limit that the matrix must be unitary.
# We provide the `is_unitary()` method to check if the matrix of gate is unitary.

umg = UMG(dim, mat=torch.randn(dim, dim)).on(2)
print(f"umg.matrix:\n{umg.matrix()}")
print(f"is_unitary: {umg.is_unitary()}")

umg.matrix:
[[-0.51127821+0.j  0.74557179+0.j -2.12760663+0.j]
 [ 0.26631397+0.j  0.22292879+0.j -0.29672673+0.j]
 [-0.09701117+0.j -1.30566788+0.j -1.42084384+0.j]]
is_unitary: False


In [14]:
circ = Circuit(3, 3, gates=[RX(3, [0, 1], pr='pr').on(0)])
circ.get_parameters()

{'pr': 0.0}